---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: appzz1220/tetrasdasdasisv2:latest
        ports:
        - containerPort: 30asdasd00   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  selector:
    app: tetris
  ports:
  - protocol: TCP
    port: 80asdasd                 # Expose port 80
    targetPort: 300sadasd0
  type: ClusterIP

