---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: appzz12werwer20/tetrisv2:latest
        ports:
        - containerPort: 3werwer000   # Use port 30werwerwe00

---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  selector:
    app: tetris
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 30werwerwer00
  type: ClusterIP

